pip install Pillow
pip install pyperclip
pip install wxPython
pip install paramiko
pip install imageio
pip install imageio-ffmpeg
pip install psutil
pip install pywin32
pip install termcolor
pip install requests